// This file is auto-generated by @hey-api/openapi-ts

export const Body_authentication_v1_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_authentication_v1_auth_login_post'
} as const;

export const Body_login_for_access_token_v1_auth_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_for_access_token_v1_auth_token_post'
} as const;

export const Body_upload_image_v1_images_upload_postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File',
            description: 'Image file to upload'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_image_v1_images_upload_post'
} as const;

export const ChangedPasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'ChangedPassword'
} as const;

export const EventCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        event_type: {
            type: 'string',
            title: 'Event Type'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        ticket_types: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/TicketTypeInput'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket Types'
        },
        start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date-time',
            title: 'End Date'
        },
        booking_start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Booking Start Date'
        },
        booking_end_date: {
            type: 'string',
            format: 'date-time',
            title: 'Booking End Date'
        }
    },
    type: 'object',
    required: ['name', 'description', 'event_type', 'start_date', 'end_date', 'booking_start_date', 'booking_end_date'],
    title: 'EventCreate'
} as const;

export const EventResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        image_id: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PydanticObjectId'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        event_type: {
            type: 'string',
            title: 'Event Type'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date-time',
            title: 'End Date'
        },
        booking_start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Booking Start Date'
        },
        booking_end_date: {
            type: 'string',
            format: 'date-time',
            title: 'Booking End Date'
        },
        created_by: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PydanticObjectId'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            '$ref': '#/components/schemas/PydanticObjectId'
        },
        ticket_types: {
            items: {
                '$ref': '#/components/schemas/TicketTypeDB'
            },
            type: 'array',
            title: 'Ticket Types',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'description', 'event_type', 'start_date', 'end_date', 'booking_start_date', 'booking_end_date', 'id'],
    title: 'EventResponse'
} as const;

export const EventUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        image_id: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PydanticObjectId'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        event_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Type'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        booking_start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking Start Date'
        },
        booking_end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking End Date'
        },
        ticket_types: {
            anyOf: [
                {
                    items: {
                        anyOf: [
                            {
                                '$ref': '#/components/schemas/TicketTypeInput'
                            },
                            {
                                '$ref': '#/components/schemas/TicketTypeDB'
                            }
                        ]
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ticket Types'
        }
    },
    type: 'object',
    title: 'EventUpdate'
} as const;

export const FilePathSchema = {
    properties: {
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        file_id: {
            '$ref': '#/components/schemas/PydanticObjectId'
        }
    },
    type: 'object',
    required: ['file_name', 'content_type', 'file_id'],
    title: 'FilePath'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        errors: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageUploadResponseSchema = {
    properties: {
        id: {
            '$ref': '#/components/schemas/PydanticObjectId'
        },
        document_id: {
            '$ref': '#/components/schemas/PydanticObjectId'
        },
        file_path: {
            '$ref': '#/components/schemas/FilePath'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        upload_date: {
            type: 'string',
            format: 'date-time',
            title: 'Upload Date'
        }
    },
    type: 'object',
    required: ['id', 'document_id', 'file_path', 'content_type', 'upload_date'],
    title: 'ImageUploadResponse'
} as const;

export const Page_EventResponse_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/EventResponse'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total'
        },
        page: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page'
        },
        size: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        pages: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pages'
        }
    },
    type: 'object',
    required: ['items', 'total', 'page', 'size'],
    title: 'Page[EventResponse]'
} as const;

export const PydanticObjectIdSchema = {
    type: 'string',
    maxLength: 24,
    minLength: 24,
    pattern: '^[0-9a-f]{24}$',
    example: '5eb7cf5a86d9755df3a6c593'
} as const;

export const RegisteredUserSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email',
            example: 'admin@email.local'
        },
        username: {
            type: 'string',
            title: 'Username',
            example: 'admin'
        },
        first_name: {
            type: 'string',
            title: 'First Name',
            example: 'Firstname'
        },
        last_name: {
            type: 'string',
            title: 'Last Name',
            example: 'Lastname'
        },
        status: {
            type: 'string',
            title: 'Status',
            example: 'active'
        },
        credit: {
            type: 'integer',
            title: 'Credit',
            example: 100
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        password: {
            type: 'string',
            title: 'Password',
            example: 'password'
        },
        confirm_password: {
            type: 'string',
            title: 'Confirm Password',
            example: 'confirm_password'
        }
    },
    type: 'object',
    required: ['email', 'username', 'first_name', 'last_name', 'status', 'credit', 'password', 'confirm_password'],
    title: 'RegisteredUser'
} as const;

export const TicketTypeDBSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        remaining: {
            type: 'integer',
            title: 'Remaining'
        },
        ticket_id: {
            type: 'string',
            title: 'Ticket Id'
        }
    },
    type: 'object',
    required: ['name', 'total', 'price', 'remaining'],
    title: 'TicketTypeDB'
} as const;

export const TicketTypeInputSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        remaining: {
            type: 'integer',
            title: 'Remaining'
        }
    },
    type: 'object',
    required: ['name', 'total', 'price', 'remaining'],
    title: 'TicketTypeInput'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        scope: {
            type: 'string',
            title: 'Scope'
        },
        issued_at: {
            type: 'string',
            format: 'date-time',
            title: 'Issued At'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'token_type', 'expires_in', 'expires_at', 'scope', 'issued_at'],
    title: 'Token'
} as const;

export const UpdatedUserSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email',
            example: 'admin@email.local'
        },
        username: {
            type: 'string',
            title: 'Username',
            example: 'admin'
        },
        first_name: {
            type: 'string',
            title: 'First Name',
            example: 'Firstname'
        },
        last_name: {
            type: 'string',
            title: 'Last Name',
            example: 'Lastname'
        },
        status: {
            type: 'string',
            title: 'Status',
            example: 'active'
        },
        credit: {
            type: 'integer',
            title: 'Credit',
            example: 100
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['email', 'username', 'first_name', 'last_name', 'status', 'credit', 'roles'],
    title: 'UpdatedUser'
} as const;

export const UserSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email',
            example: 'admin@email.local'
        },
        username: {
            type: 'string',
            title: 'Username',
            example: 'admin'
        },
        first_name: {
            type: 'string',
            title: 'First Name',
            example: 'Firstname'
        },
        last_name: {
            type: 'string',
            title: 'Last Name',
            example: 'Lastname'
        },
        status: {
            type: 'string',
            title: 'Status',
            example: 'active'
        },
        credit: {
            type: 'integer',
            title: 'Credit',
            example: 100
        },
        id: {
            '$ref': '#/components/schemas/PydanticObjectId'
        },
        last_login_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login Date',
            example: '2023-01-01T00:00:00.000000'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['email', 'username', 'first_name', 'last_name', 'status', 'credit', 'roles'],
    title: 'User'
} as const;

export const UserListSchema = {
    properties: {
        users: {
            items: {
                '$ref': '#/components/schemas/User'
            },
            type: 'array',
            title: 'Users'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        current_page: {
            type: 'integer',
            title: 'Current Page',
            default: 0
        },
        total_page: {
            type: 'integer',
            title: 'Total Page',
            default: 0
        }
    },
    type: 'object',
    required: ['users', 'count'],
    title: 'UserList'
} as const;

export const UserTicketDetailResponseSchema = {
    properties: {
        id: {
            '$ref': '#/components/schemas/PydanticObjectId'
        },
        ticket_type_id: {
            type: 'string',
            title: 'Ticket Type Id'
        },
        ticket_name: {
            type: 'string',
            title: 'Ticket Name'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        price_per_ticket: {
            type: 'integer',
            title: 'Price Per Ticket'
        },
        total_price: {
            type: 'integer',
            title: 'Total Price'
        },
        event_start_date: {
            type: 'string',
            format: 'date-time',
            title: 'Event Start Date'
        },
        event_end_date: {
            type: 'string',
            format: 'date-time',
            title: 'Event End Date'
        },
        purchase_date: {
            type: 'string',
            format: 'date-time',
            title: 'Purchase Date'
        },
        is_checked_in: {
            type: 'boolean',
            title: 'Is Checked In'
        },
        checked_in_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Checked In Date'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        user: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/User'
                },
                {
                    type: 'null'
                }
            ]
        },
        event: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'ticket_type_id', 'ticket_name', 'quantity', 'price_per_ticket', 'total_price', 'event_start_date', 'event_end_date', 'purchase_date', 'is_checked_in', 'checked_in_date', 'status'],
    title: 'UserTicketDetailResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;