// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer, formDataBodySerializer } from '@hey-api/client-fetch';
import type { HealthData, LoginForAccessTokenData, LoginForAccessTokenResponse, LoginForAccessTokenError, AuthenticationData, AuthenticationResponse, AuthenticationError, RefreshTokenData, UploadImageData, UploadImageResponse, UploadImageError, DeleteImageData, DeleteImageResponse, DeleteImageError, GetImageData, GetImageError, GetUserTicketByIdData, GetUserTicketByIdResponse, GetUserTicketByIdError, GetUserTicketsData, GetUserTicketsResponse, GetUserTicketsError, GetEventsData, GetEventsResponse, GetEventsError, CreateEventData, CreateEventResponse, CreateEventError, DeleteEventData, DeleteEventResponse, DeleteEventError, GetEventByIdData, GetEventByIdResponse, GetEventByIdError, UpdateEventData, UpdateEventResponse, UpdateEventError, GetMeData, GetMeResponse, GetByIdData, GetByIdResponse, GetByIdError, GetAllData, GetAllResponse, GetAllError, CreateData, CreateResponse, CreateError, ChangePasswordData, ChangePasswordResponse, ChangePasswordError, UpdateData, UpdateResponse, UpdateError, SetStatusData, SetStatusResponse, SetStatusError, SetRoleData, SetRoleResponse, SetRoleError } from './types.gen';
import { client as _heyApiClient } from './client.gen';
import { loginForAccessTokenResponseTransformer, authenticationResponseTransformer, uploadImageResponseTransformer, getUserTicketByIdResponseTransformer, getUserTicketsResponseTransformer, getEventsResponseTransformer, createEventResponseTransformer, getEventByIdResponseTransformer, updateEventResponseTransformer, getMeResponseTransformer, getByIdResponseTransformer, getAllResponseTransformer, createResponseTransformer, changePasswordResponseTransformer, updateResponseTransformer, setStatusResponseTransformer, setRoleResponseTransformer } from './transformers.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Get OAuth2 access token
 */
export const loginForAccessToken = <ThrowOnError extends boolean = false>(options: Options<LoginForAccessTokenData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginForAccessTokenResponse, LoginForAccessTokenError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        responseTransformer: loginForAccessTokenResponseTransformer,
        url: '/v1/auth/token',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Authentication
 */
export const authentication = <ThrowOnError extends boolean = false>(options: Options<AuthenticationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthenticationResponse, AuthenticationError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        responseTransformer: authenticationResponseTransformer,
        url: '/v1/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Refresh Token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/auth/refresh_token',
        ...options
    });
};

/**
 * Upload an image
 * Upload an image to GridFS.
 *
 * - **file**: The image file (jpeg, png, gif, webp)
 * - **event_id**: Optional event ID to link the image to an event
 *
 * Returns the uploaded image details including file_id and document_id.
 */
export const uploadImage = <ThrowOnError extends boolean = false>(options: Options<UploadImageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UploadImageResponse, UploadImageError, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: uploadImageResponseTransformer,
        url: '/v1/images/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Delete an image
 * Delete an image from GridFS and the database.
 *
 * - **image_id**: The Image document ID
 *
 * Requires authentication.
 */
export const deleteImage = <ThrowOnError extends boolean = false>(options: Options<DeleteImageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteImageResponse, DeleteImageError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/images/{image_id}',
        ...options
    });
};

/**
 * Get an image
 * Retrieve an image from GridFS by its document ID.
 *
 * - **image_id**: The Image document ID
 *
 * Returns the image file as a stream.
 */
export const getImage = <ThrowOnError extends boolean = false>(options: Options<GetImageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, GetImageError, ThrowOnError>({
        url: '/v1/images/{image_id}',
        ...options
    });
};

/**
 * Get User Ticket By Id
 */
export const getUserTicketById = <ThrowOnError extends boolean = false>(options: Options<GetUserTicketByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserTicketByIdResponse, GetUserTicketByIdError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getUserTicketByIdResponseTransformer,
        url: '/v1/user_tickets/{user_ticket_id}',
        ...options
    });
};

/**
 * Get User Tickets
 */
export const getUserTickets = <ThrowOnError extends boolean = false>(options?: Options<GetUserTicketsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserTicketsResponse, GetUserTicketsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getUserTicketsResponseTransformer,
        url: '/v1/user_tickets',
        ...options
    });
};

/**
 * Get Events
 */
export const getEvents = <ThrowOnError extends boolean = false>(options?: Options<GetEventsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetEventsResponse, GetEventsError, ThrowOnError>({
        responseTransformer: getEventsResponseTransformer,
        url: '/v1/events',
        ...options
    });
};

/**
 * Create Event
 */
export const createEvent = <ThrowOnError extends boolean = false>(options: Options<CreateEventData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateEventResponse, CreateEventError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: createEventResponseTransformer,
        url: '/v1/events',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Event
 */
export const deleteEvent = <ThrowOnError extends boolean = false>(options: Options<DeleteEventData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteEventResponse, DeleteEventError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/events/{event_id}',
        ...options
    });
};

/**
 * Get Event By Id
 */
export const getEventById = <ThrowOnError extends boolean = false>(options: Options<GetEventByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEventByIdResponse, GetEventByIdError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getEventByIdResponseTransformer,
        url: '/v1/events/{event_id}',
        ...options
    });
};

/**
 * Update Event
 */
export const updateEvent = <ThrowOnError extends boolean = false>(options: Options<UpdateEventData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateEventResponse, UpdateEventError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: updateEventResponseTransformer,
        url: '/v1/events/{event_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Me
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getMeResponseTransformer,
        url: '/v1/users/me',
        ...options
    });
};

/**
 * Get By Id
 */
export const getById = <ThrowOnError extends boolean = false>(options: Options<GetByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetByIdResponse, GetByIdError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getByIdResponseTransformer,
        url: '/v1/users/{user_id}',
        ...options
    });
};

/**
 * Get All
 */
export const getAll = <ThrowOnError extends boolean = false>(options?: Options<GetAllData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllResponse, GetAllError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getAllResponseTransformer,
        url: '/v1/users',
        ...options
    });
};

/**
 * Create
 */
export const create = <ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateResponse, CreateError, ThrowOnError>({
        responseTransformer: createResponseTransformer,
        url: '/v1/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Change Password
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<ChangePasswordResponse, ChangePasswordError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: changePasswordResponseTransformer,
        url: '/v1/users/{user_id}/change_password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update
 */
export const update = <ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateResponse, UpdateError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: updateResponseTransformer,
        url: '/v1/users/{user_id}/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Set Status
 */
export const setStatus = <ThrowOnError extends boolean = false>(options: Options<SetStatusData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<SetStatusResponse, SetStatusError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: setStatusResponseTransformer,
        url: '/v1/users/{user_id}/set_status',
        ...options
    });
};

/**
 * Set Role
 */
export const setRole = <ThrowOnError extends boolean = false>(options: Options<SetRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<SetRoleResponse, SetRoleError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: setRoleResponseTransformer,
        url: '/v1/users/{user_id}/set_role',
        ...options
    });
};