// This file is auto-generated by @hey-api/openapi-ts

import type { LoginForAccessTokenResponse, AuthenticationResponse, GetUserTicketByIdResponse, GetUserTicketsResponse, GetEventsResponse, CreateEventResponse, GetEventByIdResponse, GetMeResponse, GetByIdResponse, GetAllResponse, CreateResponse, ChangePasswordResponse, UpdateResponse, SetStatusResponse, SetRoleResponse } from './types.gen';

const tokenSchemaResponseTransformer = (data: any) => {
    data.expires_at = new Date(data.expires_at);
    data.issued_at = new Date(data.issued_at);
    return data;
};

export const loginForAccessTokenResponseTransformer = async (data: any): Promise<LoginForAccessTokenResponse> => {
    data = tokenSchemaResponseTransformer(data);
    return data;
};

export const authenticationResponseTransformer = async (data: any): Promise<AuthenticationResponse> => {
    data = tokenSchemaResponseTransformer(data);
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    if (data.last_login_date) {
        data.last_login_date = new Date(data.last_login_date);
    }
    return data;
};

const eventResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    data.end_date = new Date(data.end_date);
    data.booking_start_date = new Date(data.booking_start_date);
    data.booking_end_date = new Date(data.booking_end_date);
    return data;
};

const userTicketDetailResponseSchemaResponseTransformer = (data: any) => {
    data.event_start_date = new Date(data.event_start_date);
    data.event_end_date = new Date(data.event_end_date);
    data.purchase_date = new Date(data.purchase_date);
    if (data.checked_in_date) {
        data.checked_in_date = new Date(data.checked_in_date);
    }
    if (data.user) {
        data.user = userSchemaResponseTransformer(data.user);
    }
    if (data.event) {
        data.event = eventResponseSchemaResponseTransformer(data.event);
    }
    return data;
};

export const getUserTicketByIdResponseTransformer = async (data: any): Promise<GetUserTicketByIdResponse> => {
    data = userTicketDetailResponseSchemaResponseTransformer(data);
    return data;
};

export const getUserTicketsResponseTransformer = async (data: any): Promise<GetUserTicketsResponse> => {
    data = data.map((item: any) => {
        return userTicketDetailResponseSchemaResponseTransformer(item);
    });
    return data;
};

const pageEventResponseSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return eventResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const getEventsResponseTransformer = async (data: any): Promise<GetEventsResponse> => {
    data = pageEventResponseSchemaResponseTransformer(data);
    return data;
};

export const createEventResponseTransformer = async (data: any): Promise<CreateEventResponse> => {
    data = eventResponseSchemaResponseTransformer(data);
    return data;
};

export const getEventByIdResponseTransformer = async (data: any): Promise<GetEventByIdResponse> => {
    data = eventResponseSchemaResponseTransformer(data);
    return data;
};

export const getMeResponseTransformer = async (data: any): Promise<GetMeResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const getByIdResponseTransformer = async (data: any): Promise<GetByIdResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const userListSchemaResponseTransformer = (data: any) => {
    data.users = data.users.map((item: any) => {
        return userSchemaResponseTransformer(item);
    });
    return data;
};

export const getAllResponseTransformer = async (data: any): Promise<GetAllResponse> => {
    data = userListSchemaResponseTransformer(data);
    return data;
};

export const createResponseTransformer = async (data: any): Promise<CreateResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const changePasswordResponseTransformer = async (data: any): Promise<ChangePasswordResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const updateResponseTransformer = async (data: any): Promise<UpdateResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const setStatusResponseTransformer = async (data: any): Promise<SetStatusResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const setRoleResponseTransformer = async (data: any): Promise<SetRoleResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};