// This file is auto-generated by @hey-api/openapi-ts

import type { DeleteOrganizerResponse, GetOrganizerCompleteInfoResponse, GetStaffInOrganizerResponse, GetCoManagerInOrganizerResponse, SearchUserResponse, GetEventRelatedWithOrganizerResponse, GetHardTicketsByOrganizerAndEventIdResponse, GetOrdersByOrganizerResponse, CreateHardTicketResponse, GetRenderedTicketsResponse, CreateOrderResponse, UpdateOrderResponse, GetMeResponse, GetByIdResponse, GetAllResponse, CreateResponse, ChangePasswordResponse, UpdateResponse, SetStatusResponse, SetRoleResponse, GetTicketsByUserIdResponse, GetOrdersByUserIdResponse, CreateTicketResponse, GetTicketInfoResponse, UpdateTicketResponse, ScanTicketResponse, SignUpTicketResponse2, GetEventByIdResponse, PartialUpdateEventByIdResponse, UpdateAllDocumentInEventByIdResponse, GetAllEventsResponse, CreateEventResponse, GetEventOverviewResponse, GetTicketsByEventIdResponse, GetScanLogDashboardResponse, GetTicketVerificationLogsResponse, GetPublicTicketVerificationLogsResponse, PublicCheckInResponse2, LoginForAccessTokenResponse, AuthenticationResponse, CreateTicketTypeResponse, AddTicketDateResponse, RemoveTicketDateResponse } from './types.gen';

const hetuModelsOrganizerModelOrganizerSchemaResponseTransformer = (data: any) => {
    if (data.created_date) {
        data.created_date = new Date(data.created_date);
    }
    return data;
};

export const deleteOrganizerResponseTransformer = async (data: any): Promise<DeleteOrganizerResponse> => {
    data = hetuModelsOrganizerModelOrganizerSchemaResponseTransformer(data);
    return data;
};

const staffOutputSchemaResponseTransformer = (data: any) => {
    if (data.added_date) {
        data.added_date = new Date(data.added_date);
    }
    return data;
};

const checkInSlotSchemaResponseTransformer = (data: any) => {
    data.start_time = new Date(data.start_time);
    data.end_time = new Date(data.end_time);
    return data;
};

const eventInfoSchemaResponseTransformer = (data: any) => {
    if (data.start_date) {
        data.start_date = new Date(data.start_date);
    }
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    if (data.staffs_ids) {
        data.staffs_ids = data.staffs_ids.map((item: any) => {
            return staffOutputSchemaResponseTransformer(item);
        });
    }
    if (data.check_in_range) {
        data.check_in_range = data.check_in_range.map((item: any) => {
            return checkInSlotSchemaResponseTransformer(item);
        });
    }
    return data;
};

const organizerCompleteInfoSchemaResponseTransformer = (data: any) => {
    if (data.events) {
        data.events = data.events.map((item: any) => {
            return eventInfoSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getOrganizerCompleteInfoResponseTransformer = async (data: any): Promise<GetOrganizerCompleteInfoResponse> => {
    data = organizerCompleteInfoSchemaResponseTransformer(data);
    return data;
};

const userSchemaResponseTransformer = (data: any) => {
    if (data.last_login_date) {
        data.last_login_date = new Date(data.last_login_date);
    }
    return data;
};

export const getStaffInOrganizerResponseTransformer = async (data: any): Promise<GetStaffInOrganizerResponse> => {
    data = data.map((item: any) => {
        return userSchemaResponseTransformer(item);
    });
    return data;
};

export const getCoManagerInOrganizerResponseTransformer = async (data: any): Promise<GetCoManagerInOrganizerResponse> => {
    data = data.map((item: any) => {
        return userSchemaResponseTransformer(item);
    });
    return data;
};

export const searchUserResponseTransformer = async (data: any): Promise<SearchUserResponse> => {
    data = data.map((item: any) => {
        return userSchemaResponseTransformer(item);
    });
    return data;
};

const eventResponseSchemaResponseTransformer = (data: any) => {
    if (data.start_date) {
        data.start_date = new Date(data.start_date);
    }
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    if (data.staffs_ids) {
        data.staffs_ids = data.staffs_ids.map((item: any) => {
            return staffOutputSchemaResponseTransformer(item);
        });
    }
    if (data.check_in_range) {
        data.check_in_range = data.check_in_range.map((item: any) => {
            return checkInSlotSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getEventRelatedWithOrganizerResponseTransformer = async (data: any): Promise<GetEventRelatedWithOrganizerResponse> => {
    data = data.map((item: any) => {
        return eventResponseSchemaResponseTransformer(item);
    });
    return data;
};

const dateRangeSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    data.end_date = new Date(data.end_date);
    return data;
};

const ticketDatetypeSchemaResponseTransformer = (data: any) => {
    if (data.date_range) {
        data.date_range = dateRangeSchemaResponseTransformer(data.date_range);
    }
    if (data.single_date) {
        data.single_date = new Date(data.single_date);
    }
    return data;
};

const hardTicketDetailSchemaResponseTransformer = (data: any) => {
    data.ticket_date_type = ticketDatetypeSchemaResponseTransformer(data.ticket_date_type);
    return data;
};

export const getHardTicketsByOrganizerAndEventIdResponseTransformer = async (data: any): Promise<GetHardTicketsByOrganizerAndEventIdResponse> => {
    data = data.map((item: any) => {
        return hardTicketDetailSchemaResponseTransformer(item);
    });
    return data;
};

const orderResponseSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date) {
        data.ticket_date = ticketDatetypeSchemaResponseTransformer(data.ticket_date);
    }
    data.created_date = new Date(data.created_date);
    return data;
};

export const getOrdersByOrganizerResponseTransformer = async (data: any): Promise<GetOrdersByOrganizerResponse> => {
    data = data.map((item: any) => {
        return orderResponseSchemaResponseTransformer(item);
    });
    return data;
};

const hardTicketOutputSchemaResponseTransformer = (data: any) => {
    data.ticket_date_type = ticketDatetypeSchemaResponseTransformer(data.ticket_date_type);
    if (data.created_date) {
        data.created_date = new Date(data.created_date);
    }
    return data;
};

export const createHardTicketResponseTransformer = async (data: any): Promise<CreateHardTicketResponse> => {
    data = hardTicketOutputSchemaResponseTransformer(data);
    return data;
};

const renderedTicketsSchemaResponseTransformer = (data: any) => {
    data.ticket_date_type = ticketDatetypeSchemaResponseTransformer(data.ticket_date_type);
    return data;
};

export const getRenderedTicketsResponseTransformer = async (data: any): Promise<GetRenderedTicketsResponse> => {
    data = data.map((item: any) => {
        return renderedTicketsSchemaResponseTransformer(item);
    });
    return data;
};

const hetuModelsOrderModelOrderSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date) {
        data.ticket_date = ticketDatetypeSchemaResponseTransformer(data.ticket_date);
    }
    if (data.created_date) {
        data.created_date = new Date(data.created_date);
    }
    return data;
};

export const createOrderResponseTransformer = async (data: any): Promise<CreateOrderResponse> => {
    data = hetuModelsOrderModelOrderSchemaResponseTransformer(data);
    return data;
};

const hetuSchemasOrderSchemaOrderSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date) {
        data.ticket_date = ticketDatetypeSchemaResponseTransformer(data.ticket_date);
    }
    return data;
};

export const updateOrderResponseTransformer = async (data: any): Promise<UpdateOrderResponse> => {
    data = hetuSchemasOrderSchemaOrderSchemaResponseTransformer(data);
    return data;
};

export const getMeResponseTransformer = async (data: any): Promise<GetMeResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const getByIdResponseTransformer = async (data: any): Promise<GetByIdResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const userListSchemaResponseTransformer = (data: any) => {
    data.users = data.users.map((item: any) => {
        return userSchemaResponseTransformer(item);
    });
    return data;
};

export const getAllResponseTransformer = async (data: any): Promise<GetAllResponse> => {
    data = userListSchemaResponseTransformer(data);
    return data;
};

export const createResponseTransformer = async (data: any): Promise<CreateResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const changePasswordResponseTransformer = async (data: any): Promise<ChangePasswordResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const updateResponseTransformer = async (data: any): Promise<UpdateResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const setStatusResponseTransformer = async (data: any): Promise<SetStatusResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

export const setRoleResponseTransformer = async (data: any): Promise<SetRoleResponse> => {
    data = userSchemaResponseTransformer(data);
    return data;
};

const scanlogResponseSchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const ticketInfoSchemaResponseTransformer = (data: any) => {
    if (data.allowed_dates) {
        data.allowed_dates = ticketDatetypeSchemaResponseTransformer(data.allowed_dates);
    }
    if (data.used_logs) {
        data.used_logs = data.used_logs.map((item: any) => {
            return scanlogResponseSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getTicketsByUserIdResponseTransformer = async (data: any): Promise<GetTicketsByUserIdResponse> => {
    data = data.map((item: any) => {
        return ticketInfoSchemaResponseTransformer(item);
    });
    return data;
};

const orderInfoSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date) {
        data.ticket_date = ticketDatetypeSchemaResponseTransformer(data.ticket_date);
    }
    data.created_date = new Date(data.created_date);
    return data;
};

export const getOrdersByUserIdResponseTransformer = async (data: any): Promise<GetOrdersByUserIdResponse> => {
    data = data.map((item: any) => {
        return orderInfoSchemaResponseTransformer(item);
    });
    return data;
};

const scanLogOutputSchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    if (data.verified_datetime) {
        data.verified_datetime = new Date(data.verified_datetime);
    }
    return data;
};

const ticketSchemaResponseTransformer = (data: any) => {
    if (data.used_logs) {
        data.used_logs = data.used_logs.map((item: any) => {
            return scanLogOutputSchemaResponseTransformer(item);
        });
    }
    if (data.allowed_dates) {
        data.allowed_dates = ticketDatetypeSchemaResponseTransformer(data.allowed_dates);
    }
    return data;
};

export const createTicketResponseTransformer = async (data: any): Promise<CreateTicketResponse> => {
    data = ticketSchemaResponseTransformer(data);
    return data;
};

export const getTicketInfoResponseTransformer = async (data: any): Promise<GetTicketInfoResponse> => {
    data = ticketInfoSchemaResponseTransformer(data);
    return data;
};

export const updateTicketResponseTransformer = async (data: any): Promise<UpdateTicketResponse> => {
    data = ticketSchemaResponseTransformer(data);
    return data;
};

const scanTicketSchemaResponseTransformer = (data: any) => {
    if (data.scanned_datetime) {
        data.scanned_datetime = new Date(data.scanned_datetime);
    }
    return data;
};

export const scanTicketResponseTransformer = async (data: any): Promise<ScanTicketResponse> => {
    data = scanTicketSchemaResponseTransformer(data);
    return data;
};

const signUpTicketResponseSchemaResponseTransformer = (data: any) => {
    data.signed_up_datetime = new Date(data.signed_up_datetime);
    return data;
};

export const signUpTicketResponseTransformer = async (data: any): Promise<SignUpTicketResponse2> => {
    data = signUpTicketResponseSchemaResponseTransformer(data);
    return data;
};

const ticketRemainingSchemaResponseTransformer = (data: any) => {
    if (data.date_range) {
        data.date_range = dateRangeSchemaResponseTransformer(data.date_range);
    }
    if (data.single_date) {
        data.single_date = new Date(data.single_date);
    }
    return data;
};

const hetuSchemasTicketTypeSchemaTicketTypeSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date_type) {
        data.ticket_date_type = data.ticket_date_type.map((item: any) => {
            return ticketRemainingSchemaResponseTransformer(item);
        });
    }
    return data;
};

const staffResponseSchemaResponseTransformer = (data: any) => {
    data.added_date = new Date(data.added_date);
    return data;
};

const allEventInfoSchemaResponseTransformer = (data: any) => {
    if (data.start_date) {
        data.start_date = new Date(data.start_date);
    }
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    if (data.staffs_ids) {
        data.staffs_ids = data.staffs_ids.map((item: any) => {
            return staffOutputSchemaResponseTransformer(item);
        });
    }
    if (data.check_in_range) {
        data.check_in_range = data.check_in_range.map((item: any) => {
            return checkInSlotSchemaResponseTransformer(item);
        });
    }
    if (data.ticket_types) {
        data.ticket_types = data.ticket_types.map((item: any) => {
            return hetuSchemasTicketTypeSchemaTicketTypeSchemaResponseTransformer(item);
        });
    }
    if (data.staffs) {
        data.staffs = data.staffs.map((item: any) => {
            return staffResponseSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getEventByIdResponseTransformer = async (data: any): Promise<GetEventByIdResponse> => {
    data = allEventInfoSchemaResponseTransformer(data);
    return data;
};

const eventSchemaResponseTransformer = (data: any) => {
    if (data.start_date) {
        data.start_date = new Date(data.start_date);
    }
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    if (data.staffs_ids) {
        data.staffs_ids = data.staffs_ids.map((item: any) => {
            return staffOutputSchemaResponseTransformer(item);
        });
    }
    if (data.check_in_range) {
        data.check_in_range = data.check_in_range.map((item: any) => {
            return checkInSlotSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const partialUpdateEventByIdResponseTransformer = async (data: any): Promise<PartialUpdateEventByIdResponse> => {
    data = eventSchemaResponseTransformer(data);
    return data;
};

export const updateAllDocumentInEventByIdResponseTransformer = async (data: any): Promise<UpdateAllDocumentInEventByIdResponse> => {
    data = eventSchemaResponseTransformer(data);
    return data;
};

const pageEventResponseSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return eventResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const getAllEventsResponseTransformer = async (data: any): Promise<GetAllEventsResponse> => {
    data = pageEventResponseSchemaResponseTransformer(data);
    return data;
};

export const createEventResponseTransformer = async (data: any): Promise<CreateEventResponse> => {
    data = eventResponseSchemaResponseTransformer(data);
    return data;
};

const totalSalesPerDaySchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const eventOverviewResponseSchemaResponseTransformer = (data: any) => {
    if (data.sales_graph) {
        data.sales_graph = data.sales_graph.map((item: any) => {
            return totalSalesPerDaySchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getEventOverviewResponseTransformer = async (data: any): Promise<GetEventOverviewResponse> => {
    data = eventOverviewResponseSchemaResponseTransformer(data);
    return data;
};

export const getTicketsByEventIdResponseTransformer = async (data: any): Promise<GetTicketsByEventIdResponse> => {
    data = data.map((item: any) => {
        return ticketInfoSchemaResponseTransformer(item);
    });
    return data;
};

const dateDashboardSchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const privateScanDashboardSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date_type) {
        data.ticket_date_type = data.ticket_date_type.map((item: any) => {
            return dateDashboardSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getScanLogDashboardResponseTransformer = async (data: any): Promise<GetScanLogDashboardResponse> => {
    data = data.map((item: any) => {
        return privateScanDashboardSchemaResponseTransformer(item);
    });
    return data;
};

const ticketVerificationLogSchemaResponseTransformer = (data: any) => {
    data.verified_datetime = new Date(data.verified_datetime);
    return data;
};

const pageTicketVerificationLogSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return ticketVerificationLogSchemaResponseTransformer(item);
    });
    return data;
};

export const getTicketVerificationLogsResponseTransformer = async (data: any): Promise<GetTicketVerificationLogsResponse> => {
    data = pageTicketVerificationLogSchemaResponseTransformer(data);
    return data;
};

const publicTicketVerificationLogSchemaResponseTransformer = (data: any) => {
    data.datetime = new Date(data.datetime);
    return data;
};

const pagePublicTicketVerificationLogSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return publicTicketVerificationLogSchemaResponseTransformer(item);
    });
    return data;
};

export const getPublicTicketVerificationLogsResponseTransformer = async (data: any): Promise<GetPublicTicketVerificationLogsResponse> => {
    data = pagePublicTicketVerificationLogSchemaResponseTransformer(data);
    return data;
};

const publicCheckInResponseSchemaResponseTransformer = (data: any) => {
    data.check_in_time = new Date(data.check_in_time);
    return data;
};

export const publicCheckInResponseTransformer = async (data: any): Promise<PublicCheckInResponse2> => {
    data = publicCheckInResponseSchemaResponseTransformer(data);
    return data;
};

const tokenSchemaResponseTransformer = (data: any) => {
    data.expires_at = new Date(data.expires_at);
    data.issued_at = new Date(data.issued_at);
    return data;
};

export const loginForAccessTokenResponseTransformer = async (data: any): Promise<LoginForAccessTokenResponse> => {
    data = tokenSchemaResponseTransformer(data);
    return data;
};

export const authenticationResponseTransformer = async (data: any): Promise<AuthenticationResponse> => {
    data = tokenSchemaResponseTransformer(data);
    return data;
};

const hetuModelsTicketTypeModelTicketTypeSchemaResponseTransformer = (data: any) => {
    if (data.ticket_date_type) {
        data.ticket_date_type = data.ticket_date_type.map((item: any) => {
            return ticketRemainingSchemaResponseTransformer(item);
        });
    }
    if (data.created_date) {
        data.created_date = new Date(data.created_date);
    }
    return data;
};

export const createTicketTypeResponseTransformer = async (data: any): Promise<CreateTicketTypeResponse> => {
    data = hetuModelsTicketTypeModelTicketTypeSchemaResponseTransformer(data);
    return data;
};

export const addTicketDateResponseTransformer = async (data: any): Promise<AddTicketDateResponse> => {
    data = hetuModelsTicketTypeModelTicketTypeSchemaResponseTransformer(data);
    return data;
};

export const removeTicketDateResponseTransformer = async (data: any): Promise<RemoveTicketDateResponse> => {
    data = hetuModelsTicketTypeModelTicketTypeSchemaResponseTransformer(data);
    return data;
};