// This file is auto-generated by @hey-api/openapi-ts

export type AddMemberInOrganizer = {
    user_id: string;
};

export type AddOrDeleteDate = {
    date_type: DateType;
    start_date?: Date | null;
    end_date?: Date | null;
    single_date?: Date | null;
    quantity_remaining?: number | null;
};

export type AddOrRemoveCoManagerResponse = {
    message: string;
    co_manager_id: string;
    organizer_id: string;
};

export type AddOrRemoveEventStaffResponse = {
    message: string;
    staff_id: string;
    event_id: string;
};

export type AddOrRemoveStaffResponse = {
    message: string;
    staff_id: string;
    organizer_id: string;
};

export type AddStaffToEvent = {
    user_id: string;
};

export type AffiliatedOrganizerResponse = {
    id: string;
    name: string;
    role: OrganizerRole;
    maximum_event?: number | null;
    total_event?: number;
    image_info?: ImageInfo | null;
};

export type AllEventInfo = {
    title: string;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string;
    event_category?: string | null;
    staffs_ids?: Array<StaffOutput> | null;
    check_in_range?: Array<CheckInSlot> | null;
    id: string;
    image?: ImageInfo | null;
    ticket_types?: Array<HetuSchemasTicketTypeSchemaTicketType> | null;
    organizer?: OrganizerInfo | null;
    staffs?: Array<StaffResponse> | null;
};

export type AllTicketSummary = {
    total_orders?: number | null;
    total_pending_orders?: number | null;
    total_completed_orders?: number | null;
};

export type BankingInformationModel = {
    bank_name?: string | null;
    account_number?: string | null;
    account_name?: string | null;
};

export type BodyAuthenticationV1AuthLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyLoginForAccessTokenV1AuthTokenPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyUploadImageV1EventsEventIdUploadImagePost = {
    file: Blob | File;
};

export type BodyUploadOrganizerImageV1OrganizersOrganizerIdUploadImagePost = {
    file: Blob | File;
};

export type BodyUploadSlipV1OrdersOrderIdUploadSlipPost = {
    file: Blob | File;
};

export type BusinessAddressModel = {
    company_name?: string | null;
    company_address?: string | null;
    company_phone?: string | null;
};

export type CancelOrderResponse = {
    message: string;
    order_number: string;
    order_status: OrderStatus;
};

export type ChangedPassword = {
    current_password: string;
    new_password: string;
};

export type CheckInSlot = {
    start_time: Date;
    end_time: Date;
};

export type ConfirmOrderResponse = {
    message: string;
    order_number: string;
};

export type ContactInformationModel = {
    email?: string | null;
    line_id?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    website_url?: string | null;
};

export type CreateOrder = {
    owner_name: string;
    owner_email?: string | null;
    co_owner_email?: string | null;
    owner_phone?: string | null;
    co_owner_phone?: string | null;
    co_owner_name?: string | null;
    user_id: string;
    event_id: string;
    ticket_type_id: string;
    organizer_id: string;
    total_amount: number;
    audience_per_ticket: number;
    order_status?: OrderStatus | null;
    slip_id?: string | null;
    ticket_date?: TicketDatetype | null;
    ticket_id?: string | null;
};

export type CreateTicket = {
    event_id: string;
    owner_id?: string | null;
    owner_name?: string | null;
    co_owner_name?: string | null;
    ticket_type_id?: string | null;
    audience_per_ticket: number;
    ticket_status?: string;
    used_logs?: Array<ScanLogInput>;
    allowed_dates?: TicketDatetype | null;
};

export type CreateTicketType = {
    name: string;
    price: number | null;
    description: string | null;
    event_id: string;
    max_quantity: number;
    max_user_per_order: number;
    ticket_date_type?: Array<TicketRemaining> | null;
};

export type DateDashboard = {
    date: Date;
    total_audiences: number;
    total_audiences_scanned: number;
};

export type DateRange = {
    start_date: Date;
    end_date: Date;
};

export type DateType = 'single_date' | 'date_range';

export const DateType = {
    SINGLE_DATE: 'single_date',
    DATE_RANGE: 'date_range'
} as const;

export type DeleteHardTicket = {
    message: string;
    hard_ticket_id: string;
};

export type DeleteTicket = {
    message: string;
    ticket_id: string;
};

export type DeleteTicketType = {
    message: string;
    ticket_type_name: string;
    ticket_type_id: string;
};

export type Event = {
    title: string;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string;
    event_category?: string | null;
    staffs_ids?: Array<StaffOutput> | null;
    check_in_range?: Array<CheckInSlot> | null;
};

export type EventCreate = {
    title: string;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string;
    event_category?: string | null;
    staffs_ids?: Array<StaffInput> | null;
    check_in_range?: Array<CheckInSlot> | null;
};

export type EventDelete = {
    message: string;
    event_id: string;
};

export type EventInfo = {
    title: string;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string;
    event_category?: string | null;
    staffs_ids?: Array<StaffOutput> | null;
    check_in_range?: Array<CheckInSlot> | null;
    id: string;
    image?: ImageInfo | null;
};

export type EventOverviewResponse = {
    total_sales?: number | null;
    sales_graph?: Array<TotalSalesPerDay> | null;
    all_ticket_summary?: AllTicketSummary | null;
    tickets_sold_by_types?: Array<TicketSummary> | null;
};

export type EventPartialUpdate = {
    title?: string | null;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string | null;
    event_category?: string | null;
    staffs_ids?: Array<StaffInput> | null;
    check_in_range?: Array<CheckInSlot> | null;
};

export type EventResponse = {
    title: string;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string;
    event_category?: string | null;
    staffs_ids?: Array<StaffOutput> | null;
    check_in_range?: Array<CheckInSlot> | null;
    id: string;
    image?: ImageInfo | null;
};

export type EventType = 'public' | 'private';

export const EventType = {
    PUBLIC: 'public',
    PRIVATE: 'private'
} as const;

export type EventUpdate = {
    title: string;
    description?: string | null;
    location?: string | null;
    event_type?: EventType;
    max_audience?: number | null;
    image_id?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    organizer_id?: string | null;
    event_status?: string;
    event_category?: string | null;
    staffs_ids?: Array<StaffInput> | null;
    check_in_range?: Array<CheckInSlot> | null;
};

export type GenarateHardTicketResponse = {
    message: string;
    ticket_ids: Array<string>;
};

export type HttpValidationError = {
    errors?: Array<ValidationError>;
};

export type HardTicketInput = {
    quantity_per_ticket: number;
    total_ticket: number;
    event_id: string;
    organizer_id: string;
    ticket_type_id: string;
    ticket_date_type: TicketDatetype;
    generate_status?: boolean;
    ticket_ids?: Array<string>;
};

export type HardTicketOutput = {
    _id?: string;
    quantity_per_ticket: number;
    total_ticket: number;
    event_id: string;
    organizer_id: string;
    ticket_type_id: string;
    ticket_date_type: TicketDatetype;
    generate_status?: boolean;
    ticket_ids?: Array<string>;
    created_date?: Date | null;
};

export type HardTicketDetail = {
    quantity_per_ticket: number;
    total_ticket: number;
    event_id: string;
    organizer_id: string;
    ticket_type_id: string;
    ticket_date_type: TicketDatetype;
    generate_status?: boolean;
    ticket_ids?: Array<string>;
    id: string;
    ticket_type: HetuSchemasHardTicketSchemaTicketType;
};

export type ImageInfo = {
    filename: string;
    content_type: string;
    file_id: string;
};

export type OrderInfo = {
    order_number: string;
    slip_info?: SlipInfo | null;
    event_name: string;
    ticket_type_name: string;
    total_amount: number;
    audience_per_ticket: number;
    order_status?: OrderStatus | null;
    ticket_date?: TicketDatetype | null;
    created_date: Date;
};

export type OrderResponse = {
    owner_name: string;
    owner_email?: string | null;
    co_owner_email?: string | null;
    owner_phone?: string | null;
    co_owner_phone?: string | null;
    co_owner_name?: string | null;
    user_id: string;
    event_id: string;
    ticket_type_id: string;
    organizer_id: string;
    total_amount: number;
    audience_per_ticket: number;
    order_status?: OrderStatus | null;
    slip_id?: string | null;
    ticket_date?: TicketDatetype | null;
    ticket_id?: string | null;
    id: string;
    ticket_type_name: string;
    order_number: string;
    slip_info?: SlipInfo | null;
    created_date: Date;
};

export type OrderStatus = 'not_paid' | 'pending' | 'completed' | 'cancelled';

export const OrderStatus = {
    NOT_PAID: 'not_paid',
    PENDING: 'pending',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled'
} as const;

export type OrganizerCompleteInfo = {
    organizer: OrganizerResponse;
    manager: UserInfo;
    co_managers?: Array<UserInfo>;
    staff_members?: Array<UserInfo>;
    events?: Array<EventInfo>;
};

export type OrganizerCreate = {
    name: string;
    manager_id: string;
    co_manager_id: Array<string> | null;
    staffs_id: Array<string> | null;
    maximum_event?: number | null;
    contact_information: ContactInformationModel | null;
    business_address: BusinessAddressModel | null;
    banking_information: BankingInformationModel | null;
    image_id?: string | null;
};

export type OrganizerInfo = {
    id: string;
    name: string;
};

export type OrganizerResponse = {
    name: string;
    manager_id: string;
    co_manager_id: Array<string> | null;
    staffs_id: Array<string> | null;
    maximum_event?: number | null;
    contact_information: ContactInformationModel | null;
    business_address: BusinessAddressModel | null;
    banking_information: BankingInformationModel | null;
    image_id?: string | null;
    id: string;
};

export type OrganizerRole = 'manager' | 'co_manager' | 'staff';

export const OrganizerRole = {
    MANAGER: 'manager',
    CO_MANAGER: 'co_manager',
    STAFF: 'staff'
} as const;

export type PageEventResponse = {
    items: Array<EventResponse>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
};

export type PagePublicTicketVerificationLog = {
    items: Array<PublicTicketVerificationLog>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
};

export type PageTicketVerificationLog = {
    items: Array<TicketVerificationLog>;
    total?: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
};

export type PartialUpdateOrder = {
    owner_name?: string | null;
    owner_email?: string | null;
    co_owner_email?: string | null;
    owner_phone?: string | null;
    co_owner_phone?: string | null;
    co_owner_name?: string | null;
    user_id?: string | null;
    event_id?: string | null;
    ticket_type_id?: string | null;
    organizer_id?: string | null;
    total_amount?: number | null;
    audience_per_ticket?: number | null;
    order_status?: OrderStatus | null;
    slip_id?: string | null;
};

export type PatchOrganizer = {
    name?: string | null;
    manager_id?: string | null;
    co_manager_id?: Array<string> | null;
    staffs_id?: Array<string> | null;
    maximum_event?: number | null;
    contact_information?: ContactInformationModel | null;
    business_address?: BusinessAddressModel | null;
    banking_information?: BankingInformationModel | null;
    image_id?: string | null;
};

export type PatchTicket = {
    event_id: string | null;
    owner_id?: string | null;
    owner_name: string | null;
    co_owner_name: string | null;
    ticket_type_id: string | null;
    audience_per_ticket: number | null;
    ticket_status?: string;
    expired_date?: Date | null;
    used_logs: Array<ScanLogInput> | null;
};

export type PrivateScanDashboard = {
    ticket_type: string;
    ticket_date_type?: Array<DateDashboard> | null;
    total_audiences: number;
    total_audiences_scanned: number;
};

export type PublicCheckInResponse = {
    message: string;
    event_name: string;
    owner_name: string;
    check_in_time: Date;
};

export type PublicScanDashboard = {
    ticket_type: string;
    total_audience: number;
};

export type PublicTicketVerificationLog = {
    owner_name: string;
    datetime: Date;
};

export type RegisteredUser = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    status: string;
    password: string;
    confirm_password: string;
};

export type RenderedTickets = {
    ticket_id: string;
    ticket_name: string;
    audience_per_ticket: number;
    ticket_status: string;
    ticket_date_type: TicketDatetype;
};

export type ScanLogInput = {
    date: Date;
    verified_by: string;
    verified_datetime?: Date;
};

export type ScanLogOutput = {
    date: Date;
    verified_by: string;
    verified_datetime?: Date;
};

export type ScanTicket = {
    message: string;
    ticket_id: string;
    scanned_by: string;
    scanned_datetime?: Date | null;
};

export type ScanlogResponse = {
    date: Date;
    verified_by?: string | null;
};

export type SignUpTicketResponse = {
    message: string;
    ticket_id: string;
    owner_id: string;
    signed_up_datetime: Date;
};

export type SlipInfo = {
    filename: string;
    content_type: string;
    file_id: string;
};

export type SlipUploadResponse = {
    message: string;
    order_id: string;
    order_number: string;
};

export type StaffInput = {
    id: string;
    added_date?: Date;
};

export type StaffOutput = {
    id: string;
    added_date?: Date;
};

export type StaffResponse = {
    id: string;
    username: string;
    first_name: string;
    last_name: string;
    email: string;
    added_date: Date;
};

export type Ticket = {
    event_id: string;
    owner_id?: string | null;
    owner_name?: string | null;
    co_owner_name?: string | null;
    ticket_type_id?: string | null;
    audience_per_ticket: number;
    ticket_status?: string;
    used_logs?: Array<ScanLogOutput>;
    allowed_dates?: TicketDatetype | null;
};

export type TicketDatetype = {
    date_range?: DateRange | null;
    single_date?: Date | null;
};

export type TicketInfo = {
    id: string;
    event_image?: ImageInfo | null;
    event_name?: string | null;
    ticket_type_name?: string | null;
    ticket_status?: string | null;
    owner_name?: string | null;
    co_owner_name?: string | null;
    location?: string | null;
    total_audience?: number | null;
    price?: number | null;
    allowed_dates?: TicketDatetype | null;
    used_logs?: Array<ScanlogResponse> | null;
};

export type TicketRemaining = {
    date_range?: DateRange | null;
    single_date?: Date | null;
    quantity_remaining: number;
};

export type TicketSummary = {
    ticket_type_name?: string | null;
    total_sales?: number | null;
    total_completed_orders?: number | null;
    total_pending_orders?: number | null;
    total_canceled_orders?: number | null;
    total_tickets?: number | null;
    total_tickets_remaining?: number | null;
};

export type TicketVerificationLog = {
    event_name: string;
    ticket_type: string;
    owner_name: string;
    verified_by: string;
    verified_datetime: Date;
};

export type Token = {
    access_token: string;
    refresh_token: string;
    token_type: string;
    expires_in: number;
    expires_at: Date;
    scope: string;
    issued_at: Date;
};

export type TotalSalesPerDay = {
    date: Date;
    total_sales?: number | null;
};

export type UpdatedUser = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    status: string;
    roles: Array<string>;
};

export type User = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    status: string;
    id?: string;
    last_login_date?: Date | null;
    roles: Array<string>;
};

export type UserInfo = {
    id: string;
    username: string;
    email: string;
    first_name?: string | null;
    last_name?: string | null;
};

export type UserList = {
    users: Array<User>;
    count: number;
    current_page?: number;
    total_page?: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type HetuModelsOrderModelOrder = {
    _id?: string;
    owner_name: string;
    owner_email?: string | null;
    co_owner_email?: string | null;
    owner_phone?: string | null;
    co_owner_phone?: string | null;
    co_owner_name?: string | null;
    user_id: string;
    event_id: string;
    ticket_type_id: string;
    organizer_id: string;
    total_amount: number;
    audience_per_ticket: number;
    order_status?: OrderStatus | null;
    slip_id?: string | null;
    ticket_date?: TicketDatetype | null;
    ticket_id?: string | null;
    order_number: string;
    created_date?: Date | null;
};

export type HetuModelsOrganizerModelOrganizer = {
    _id?: string;
    name: string;
    manager_id: string;
    co_manager_id?: Array<string>;
    staffs_id?: Array<string>;
    maximum_event?: number | null;
    contact_information?: ContactInformationModel | null;
    business_address?: BusinessAddressModel | null;
    banking_information?: BankingInformationModel | null;
    image_id?: string | null;
    created_date?: Date | null;
};

export type HetuModelsTicketTypeModelTicketType = {
    _id?: string;
    name: string;
    price: number | null;
    description: string | null;
    event_id: string;
    max_quantity: number;
    max_user_per_order: number;
    ticket_date_type?: Array<TicketRemaining> | null;
    created_date?: Date | null;
};

export type HetuSchemasHardTicketSchemaTicketType = {
    ticket_type: string;
    total_price: number;
};

export type HetuSchemasOrderSchemaOrder = {
    owner_name: string;
    owner_email?: string | null;
    co_owner_email?: string | null;
    owner_phone?: string | null;
    co_owner_phone?: string | null;
    co_owner_name?: string | null;
    user_id: string;
    event_id: string;
    ticket_type_id: string;
    organizer_id: string;
    total_amount: number;
    audience_per_ticket: number;
    order_status?: OrderStatus | null;
    slip_id?: string | null;
    ticket_date?: TicketDatetype | null;
    ticket_id?: string | null;
    order_number: string;
};

export type HetuSchemasOrganizerSchemaOrganizer = {
    name: string;
    manager_id: string;
    co_manager_id: Array<string> | null;
    staffs_id: Array<string> | null;
    maximum_event?: number | null;
    contact_information: ContactInformationModel | null;
    business_address: BusinessAddressModel | null;
    banking_information: BankingInformationModel | null;
    image_id?: string | null;
};

export type HetuSchemasTicketTypeSchemaTicketType = {
    name: string;
    price: number | null;
    description: string | null;
    event_id: string;
    max_quantity: number;
    max_user_per_order: number;
    ticket_date_type?: Array<TicketRemaining> | null;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateOrganizerData = {
    body: OrganizerCreate;
    path?: never;
    query?: never;
    url: '/v1/organizers';
};

export type CreateOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrganizerError = CreateOrganizerErrors[keyof CreateOrganizerErrors];

export type CreateOrganizerResponses = {
    /**
     * Successful Response
     */
    200: OrganizerResponse;
};

export type CreateOrganizerResponse = CreateOrganizerResponses[keyof CreateOrganizerResponses];

export type DeleteOrganizerData = {
    body?: never;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}';
};

export type DeleteOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOrganizerError = DeleteOrganizerErrors[keyof DeleteOrganizerErrors];

export type DeleteOrganizerResponses = {
    /**
     * Successful Response
     */
    200: HetuModelsOrganizerModelOrganizer;
};

export type DeleteOrganizerResponse = DeleteOrganizerResponses[keyof DeleteOrganizerResponses];

export type GetOrganizerCompleteInfoData = {
    body?: never;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}';
};

export type GetOrganizerCompleteInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizerCompleteInfoError = GetOrganizerCompleteInfoErrors[keyof GetOrganizerCompleteInfoErrors];

export type GetOrganizerCompleteInfoResponses = {
    /**
     * Successful Response
     */
    200: OrganizerCompleteInfo;
};

export type GetOrganizerCompleteInfoResponse = GetOrganizerCompleteInfoResponses[keyof GetOrganizerCompleteInfoResponses];

export type UpdateOrganizerData = {
    body: PatchOrganizer;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}';
};

export type UpdateOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrganizerError = UpdateOrganizerErrors[keyof UpdateOrganizerErrors];

export type UpdateOrganizerResponses = {
    /**
     * Successful Response
     */
    200: HetuSchemasOrganizerSchemaOrganizer;
};

export type UpdateOrganizerResponse = UpdateOrganizerResponses[keyof UpdateOrganizerResponses];

export type GetStaffInOrganizerData = {
    body?: never;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/staffs';
};

export type GetStaffInOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStaffInOrganizerError = GetStaffInOrganizerErrors[keyof GetStaffInOrganizerErrors];

export type GetStaffInOrganizerResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type GetStaffInOrganizerResponse = GetStaffInOrganizerResponses[keyof GetStaffInOrganizerResponses];

export type GetCoManagerInOrganizerData = {
    body?: never;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/co-managers';
};

export type GetCoManagerInOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCoManagerInOrganizerError = GetCoManagerInOrganizerErrors[keyof GetCoManagerInOrganizerErrors];

export type GetCoManagerInOrganizerResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type GetCoManagerInOrganizerResponse = GetCoManagerInOrganizerResponses[keyof GetCoManagerInOrganizerResponses];

export type AddStaffToOrganizerData = {
    body: AddMemberInOrganizer;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/staff';
};

export type AddStaffToOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddStaffToOrganizerError = AddStaffToOrganizerErrors[keyof AddStaffToOrganizerErrors];

export type AddStaffToOrganizerResponses = {
    /**
     * Successful Response
     */
    200: AddOrRemoveStaffResponse;
};

export type AddStaffToOrganizerResponse = AddStaffToOrganizerResponses[keyof AddStaffToOrganizerResponses];

export type DeleteStaffByOrganizerAndStaffIdData = {
    body?: never;
    path: {
        organizer_id: string;
        staff_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/staffs/{staff_id}';
};

export type DeleteStaffByOrganizerAndStaffIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStaffByOrganizerAndStaffIdError = DeleteStaffByOrganizerAndStaffIdErrors[keyof DeleteStaffByOrganizerAndStaffIdErrors];

export type DeleteStaffByOrganizerAndStaffIdResponses = {
    /**
     * Successful Response
     */
    200: AddOrRemoveStaffResponse;
};

export type DeleteStaffByOrganizerAndStaffIdResponse = DeleteStaffByOrganizerAndStaffIdResponses[keyof DeleteStaffByOrganizerAndStaffIdResponses];

export type AddCoManagerToOrganizerData = {
    body: AddMemberInOrganizer;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/co-manager';
};

export type AddCoManagerToOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCoManagerToOrganizerError = AddCoManagerToOrganizerErrors[keyof AddCoManagerToOrganizerErrors];

export type AddCoManagerToOrganizerResponses = {
    /**
     * Successful Response
     */
    200: AddOrRemoveCoManagerResponse;
};

export type AddCoManagerToOrganizerResponse = AddCoManagerToOrganizerResponses[keyof AddCoManagerToOrganizerResponses];

export type DeleteCoManagerByOrganizerAndCoManagerIdData = {
    body: AddMemberInOrganizer;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/co-managers/{co_manager_id}';
};

export type DeleteCoManagerByOrganizerAndCoManagerIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCoManagerByOrganizerAndCoManagerIdError = DeleteCoManagerByOrganizerAndCoManagerIdErrors[keyof DeleteCoManagerByOrganizerAndCoManagerIdErrors];

export type DeleteCoManagerByOrganizerAndCoManagerIdResponses = {
    /**
     * Successful Response
     */
    200: AddOrRemoveCoManagerResponse;
};

export type DeleteCoManagerByOrganizerAndCoManagerIdResponse = DeleteCoManagerByOrganizerAndCoManagerIdResponses[keyof DeleteCoManagerByOrganizerAndCoManagerIdResponses];

export type UploadOrganizerImageData = {
    body: BodyUploadOrganizerImageV1OrganizersOrganizerIdUploadImagePost;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers{organizer_id}/upload-image';
};

export type UploadOrganizerImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadOrganizerImageError = UploadOrganizerImageErrors[keyof UploadOrganizerImageErrors];

export type UploadOrganizerImageResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UploadOrganizerImageResponse = UploadOrganizerImageResponses[keyof UploadOrganizerImageResponses];

export type GetOrganizerImageData = {
    body?: never;
    path: {
        file_id: string;
    };
    query?: never;
    url: '/v1/organizers/image/{file_id}';
};

export type GetOrganizerImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrganizerImageError = GetOrganizerImageErrors[keyof GetOrganizerImageErrors];

export type GetOrganizerImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchUserData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/v1/organizers/search-user/';
};

export type SearchUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchUserError = SearchUserErrors[keyof SearchUserErrors];

export type SearchUserResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type SearchUserResponse = SearchUserResponses[keyof SearchUserResponses];

export type GetEventRelatedWithOrganizerData = {
    body?: never;
    path: {
        organizer_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/events';
};

export type GetEventRelatedWithOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventRelatedWithOrganizerError = GetEventRelatedWithOrganizerErrors[keyof GetEventRelatedWithOrganizerErrors];

export type GetEventRelatedWithOrganizerResponses = {
    /**
     * Successful Response
     */
    200: Array<EventResponse>;
};

export type GetEventRelatedWithOrganizerResponse = GetEventRelatedWithOrganizerResponses[keyof GetEventRelatedWithOrganizerResponses];

export type GetHardTicketsByOrganizerAndEventIdData = {
    body?: never;
    path: {
        organizer_id: string;
        event_id: string;
    };
    query?: never;
    url: '/v1/organizers/{organizer_id}/event/{event_id}/hard-tickets';
};

export type GetHardTicketsByOrganizerAndEventIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHardTicketsByOrganizerAndEventIdError = GetHardTicketsByOrganizerAndEventIdErrors[keyof GetHardTicketsByOrganizerAndEventIdErrors];

export type GetHardTicketsByOrganizerAndEventIdResponses = {
    /**
     * Successful Response
     */
    200: Array<HardTicketDetail>;
};

export type GetHardTicketsByOrganizerAndEventIdResponse = GetHardTicketsByOrganizerAndEventIdResponses[keyof GetHardTicketsByOrganizerAndEventIdResponses];

export type GetOrdersByOrganizerData = {
    body?: never;
    path: {
        organizer_id: string;
        event_id: string;
    };
    query?: {
        /**
         * Filter by order status (pending, completed, cancelled)
         */
        status?: OrderStatus | null;
        page?: number;
        size?: number;
    };
    url: '/v1/organizers/{organizer_id}/event/{event_id}/orders';
};

export type GetOrdersByOrganizerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrdersByOrganizerError = GetOrdersByOrganizerErrors[keyof GetOrdersByOrganizerErrors];

export type GetOrdersByOrganizerResponses = {
    /**
     * Successful Response
     */
    200: Array<OrderResponse>;
};

export type GetOrdersByOrganizerResponse = GetOrdersByOrganizerResponses[keyof GetOrdersByOrganizerResponses];

export type CreateHardTicketData = {
    body: HardTicketInput;
    path?: never;
    query?: never;
    url: '/v1/hard_ticket';
};

export type CreateHardTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateHardTicketError = CreateHardTicketErrors[keyof CreateHardTicketErrors];

export type CreateHardTicketResponses = {
    /**
     * Successful Response
     */
    200: HardTicketOutput;
};

export type CreateHardTicketResponse = CreateHardTicketResponses[keyof CreateHardTicketResponses];

export type GenerateTicketsData = {
    body?: never;
    path: {
        hard_ticket_id: string;
    };
    query?: never;
    url: '/v1/hard_ticket/{hard_ticket_id}/generate-tickets';
};

export type GenerateTicketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTicketsError = GenerateTicketsErrors[keyof GenerateTicketsErrors];

export type GenerateTicketsResponses = {
    /**
     * Successful Response
     */
    200: GenarateHardTicketResponse;
};

export type GenerateTicketsResponse = GenerateTicketsResponses[keyof GenerateTicketsResponses];

export type DeleteHardTicketData = {
    body?: never;
    path: {
        hard_ticket_id: string;
    };
    query?: never;
    url: '/v1/hard_ticket/{hard_ticket_id}';
};

export type DeleteHardTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHardTicketError = DeleteHardTicketErrors[keyof DeleteHardTicketErrors];

export type DeleteHardTicketResponses = {
    /**
     * Successful Response
     */
    200: DeleteHardTicket;
};

export type DeleteHardTicketResponse = DeleteHardTicketResponses[keyof DeleteHardTicketResponses];

export type GetRenderedTicketsData = {
    body?: never;
    path: {
        hard_ticket_id: string;
    };
    query?: never;
    url: '/v1/hard_ticket/{hard_ticket_id}/generated-tickets';
};

export type GetRenderedTicketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRenderedTicketsError = GetRenderedTicketsErrors[keyof GetRenderedTicketsErrors];

export type GetRenderedTicketsResponses = {
    /**
     * Successful Response
     */
    200: Array<RenderedTickets>;
};

export type GetRenderedTicketsResponse = GetRenderedTicketsResponses[keyof GetRenderedTicketsResponses];

export type CreateOrderData = {
    body: CreateOrder;
    path?: never;
    query?: never;
    url: '/v1/orders';
};

export type CreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export type CreateOrderResponses = {
    /**
     * Successful Response
     */
    200: HetuModelsOrderModelOrder;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];

export type UpdateOrderData = {
    body: PartialUpdateOrder;
    path: {
        order_id: string;
    };
    query?: never;
    url: '/v1/orders/{order_id}';
};

export type UpdateOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOrderError = UpdateOrderErrors[keyof UpdateOrderErrors];

export type UpdateOrderResponses = {
    /**
     * Successful Response
     */
    200: HetuSchemasOrderSchemaOrder;
};

export type UpdateOrderResponse = UpdateOrderResponses[keyof UpdateOrderResponses];

export type UploadSlipData = {
    body: BodyUploadSlipV1OrdersOrderIdUploadSlipPost;
    path: {
        order_id: string;
    };
    query?: never;
    url: '/v1/orders/{order_id}/upload-slip';
};

export type UploadSlipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSlipError = UploadSlipErrors[keyof UploadSlipErrors];

export type UploadSlipResponses = {
    /**
     * Successful Response
     */
    200: SlipUploadResponse;
};

export type UploadSlipResponse = UploadSlipResponses[keyof UploadSlipResponses];

export type ConfirmOrderData = {
    body?: never;
    path: {
        order_id: string;
    };
    query?: never;
    url: '/v1/orders/{order_id}/confirm-order';
};

export type ConfirmOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmOrderError = ConfirmOrderErrors[keyof ConfirmOrderErrors];

export type ConfirmOrderResponses = {
    /**
     * Successful Response
     */
    200: ConfirmOrderResponse;
};

export type ConfirmOrderResponse2 = ConfirmOrderResponses[keyof ConfirmOrderResponses];

export type CancelOrderData = {
    body?: never;
    path: {
        order_id: string;
    };
    query?: never;
    url: '/v1/orders/{order_id}/cancel-order';
};

export type CancelOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelOrderError = CancelOrderErrors[keyof CancelOrderErrors];

export type CancelOrderResponses = {
    /**
     * Successful Response
     */
    200: CancelOrderResponse;
};

export type CancelOrderResponse2 = CancelOrderResponses[keyof CancelOrderResponses];

export type GetSlipImageData = {
    body?: never;
    path: {
        file_id: string;
    };
    query?: never;
    url: '/v1/orders/slip-image/{file_id}';
};

export type GetSlipImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSlipImageError = GetSlipImageErrors[keyof GetSlipImageErrors];

export type GetSlipImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}';
};

export type GetByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByIdError = GetByIdErrors[keyof GetByIdErrors];

export type GetByIdResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type GetAllData = {
    body?: never;
    path?: never;
    query?: {
        current_page?: number;
        limit?: number;
        username?: string | null;
        email?: string | null;
    };
    url: '/v1/users';
};

export type GetAllErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllError = GetAllErrors[keyof GetAllErrors];

export type GetAllResponses = {
    /**
     * Successful Response
     */
    200: UserList;
};

export type GetAllResponse = GetAllResponses[keyof GetAllResponses];

export type CreateData = {
    body: RegisteredUser;
    path?: never;
    query?: never;
    url: '/v1/users/';
};

export type CreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type ChangePasswordData = {
    body: ChangedPassword;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/change_password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type UpdateData = {
    body: UpdatedUser;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/update';
};

export type UpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type SetStatusData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: {
        status?: string;
    };
    url: '/v1/users/{user_id}/set_status';
};

export type SetStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetStatusError = SetStatusErrors[keyof SetStatusErrors];

export type SetStatusResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SetStatusResponse = SetStatusResponses[keyof SetStatusResponses];

export type SetRoleData = {
    body?: never;
    path: {
        user_id: string;
    };
    query: {
        role: string;
        action: string;
    };
    url: '/v1/users/{user_id}/set_role';
};

export type SetRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRoleError = SetRoleErrors[keyof SetRoleErrors];

export type SetRoleResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SetRoleResponse = SetRoleResponses[keyof SetRoleResponses];

export type GetTicketsByUserIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/tickets';
};

export type GetTicketsByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketsByUserIdError = GetTicketsByUserIdErrors[keyof GetTicketsByUserIdErrors];

export type GetTicketsByUserIdResponses = {
    /**
     * Successful Response
     */
    200: Array<TicketInfo>;
};

export type GetTicketsByUserIdResponse = GetTicketsByUserIdResponses[keyof GetTicketsByUserIdResponses];

export type GetAffliateWithData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/organizers';
};

export type GetAffliateWithErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAffliateWithError = GetAffliateWithErrors[keyof GetAffliateWithErrors];

export type GetAffliateWithResponses = {
    /**
     * Successful Response
     */
    200: Array<AffiliatedOrganizerResponse>;
};

export type GetAffliateWithResponse = GetAffliateWithResponses[keyof GetAffliateWithResponses];

export type GetOrdersByUserIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/orders';
};

export type GetOrdersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrdersByUserIdError = GetOrdersByUserIdErrors[keyof GetOrdersByUserIdErrors];

export type GetOrdersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: Array<OrderInfo>;
};

export type GetOrdersByUserIdResponse = GetOrdersByUserIdResponses[keyof GetOrdersByUserIdResponses];

export type CreateTicketData = {
    body: CreateTicket;
    path?: never;
    query?: never;
    url: '/v1/tickets';
};

export type CreateTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketError = CreateTicketErrors[keyof CreateTicketErrors];

export type CreateTicketResponses = {
    /**
     * Successful Response
     */
    200: Ticket;
};

export type CreateTicketResponse = CreateTicketResponses[keyof CreateTicketResponses];

export type DeleteTicketByIdData = {
    body?: never;
    path: {
        ticket_id: string;
    };
    query?: never;
    url: '/v1/tickets/{ticket_id}';
};

export type DeleteTicketByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTicketByIdError = DeleteTicketByIdErrors[keyof DeleteTicketByIdErrors];

export type DeleteTicketByIdResponses = {
    /**
     * Successful Response
     */
    200: DeleteTicket;
};

export type DeleteTicketByIdResponse = DeleteTicketByIdResponses[keyof DeleteTicketByIdResponses];

export type GetTicketInfoData = {
    body?: never;
    path: {
        ticket_id: string;
    };
    query?: never;
    url: '/v1/tickets/{ticket_id}';
};

export type GetTicketInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketInfoError = GetTicketInfoErrors[keyof GetTicketInfoErrors];

export type GetTicketInfoResponses = {
    /**
     * Successful Response
     */
    200: TicketInfo;
};

export type GetTicketInfoResponse = GetTicketInfoResponses[keyof GetTicketInfoResponses];

export type UpdateTicketData = {
    body: PatchTicket;
    path: {
        ticket_id: string;
    };
    query?: never;
    url: '/v1/tickets/{ticket_id}';
};

export type UpdateTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTicketError = UpdateTicketErrors[keyof UpdateTicketErrors];

export type UpdateTicketResponses = {
    /**
     * Successful Response
     */
    200: Ticket;
};

export type UpdateTicketResponse = UpdateTicketResponses[keyof UpdateTicketResponses];

export type ScanTicketData = {
    body?: never;
    path: {
        ticket_id: string;
    };
    query?: never;
    url: '/v1/tickets/{ticket_id}/scan';
};

export type ScanTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanTicketError = ScanTicketErrors[keyof ScanTicketErrors];

export type ScanTicketResponses = {
    /**
     * Successful Response
     */
    200: ScanTicket;
};

export type ScanTicketResponse = ScanTicketResponses[keyof ScanTicketResponses];

export type SignUpTicketData = {
    body?: never;
    path: {
        ticket_id: string;
    };
    query: {
        owner_id: string;
    };
    url: '/v1/tickets/{ticket_id}/sign-up-ticket/{user_id}';
};

export type SignUpTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignUpTicketError = SignUpTicketErrors[keyof SignUpTicketErrors];

export type SignUpTicketResponses = {
    /**
     * Successful Response
     */
    200: SignUpTicketResponse;
};

export type SignUpTicketResponse2 = SignUpTicketResponses[keyof SignUpTicketResponses];

export type DeleteEventByIdData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type DeleteEventByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEventByIdError = DeleteEventByIdErrors[keyof DeleteEventByIdErrors];

export type DeleteEventByIdResponses = {
    /**
     * Successful Response
     */
    200: EventDelete;
};

export type DeleteEventByIdResponse = DeleteEventByIdResponses[keyof DeleteEventByIdResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type GetEventByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventByIdError = GetEventByIdErrors[keyof GetEventByIdErrors];

export type GetEventByIdResponses = {
    /**
     * Successful Response
     */
    200: AllEventInfo;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];

export type PartialUpdateEventByIdData = {
    body: EventPartialUpdate;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type PartialUpdateEventByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PartialUpdateEventByIdError = PartialUpdateEventByIdErrors[keyof PartialUpdateEventByIdErrors];

export type PartialUpdateEventByIdResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type PartialUpdateEventByIdResponse = PartialUpdateEventByIdResponses[keyof PartialUpdateEventByIdResponses];

export type UpdateAllDocumentInEventByIdData = {
    body: EventUpdate;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type UpdateAllDocumentInEventByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAllDocumentInEventByIdError = UpdateAllDocumentInEventByIdErrors[keyof UpdateAllDocumentInEventByIdErrors];

export type UpdateAllDocumentInEventByIdResponses = {
    /**
     * Successful Response
     */
    200: Event;
};

export type UpdateAllDocumentInEventByIdResponse = UpdateAllDocumentInEventByIdResponses[keyof UpdateAllDocumentInEventByIdResponses];

export type GetAllEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by event type
         */
        event_type?: string | null;
        /**
         * Filter by event category
         */
        event_category?: string | null;
        /**
         * Search events by title or description
         */
        search_query?: string | null;
        page?: number;
        size?: number;
    };
    url: '/v1/events';
};

export type GetAllEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllEventsError = GetAllEventsErrors[keyof GetAllEventsErrors];

export type GetAllEventsResponses = {
    /**
     * Successful Response
     */
    200: PageEventResponse;
};

export type GetAllEventsResponse = GetAllEventsResponses[keyof GetAllEventsResponses];

export type CreateEventData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/v1/events';
};

export type CreateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * Successful Response
     */
    200: EventResponse;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetEventImageData = {
    body?: never;
    path: {
        file_id: string;
    };
    query?: never;
    url: '/v1/events/image/{file_id}';
};

export type GetEventImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventImageError = GetEventImageErrors[keyof GetEventImageErrors];

export type GetEventImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadImageData = {
    body: BodyUploadImageV1EventsEventIdUploadImagePost;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/upload-image';
};

export type UploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type GetEventOverviewData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/overview';
};

export type GetEventOverviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventOverviewError = GetEventOverviewErrors[keyof GetEventOverviewErrors];

export type GetEventOverviewResponses = {
    /**
     * Successful Response
     */
    200: EventOverviewResponse;
};

export type GetEventOverviewResponse = GetEventOverviewResponses[keyof GetEventOverviewResponses];

export type GetTicketsByEventIdData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/events/{event_id}/tickets';
};

export type GetTicketsByEventIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketsByEventIdError = GetTicketsByEventIdErrors[keyof GetTicketsByEventIdErrors];

export type GetTicketsByEventIdResponses = {
    /**
     * Successful Response
     */
    200: Array<TicketInfo>;
};

export type GetTicketsByEventIdResponse = GetTicketsByEventIdResponses[keyof GetTicketsByEventIdResponses];

export type GetScanLogDashboardData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/private-scan-dashboard';
};

export type GetScanLogDashboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanLogDashboardError = GetScanLogDashboardErrors[keyof GetScanLogDashboardErrors];

export type GetScanLogDashboardResponses = {
    /**
     * Successful Response
     */
    200: Array<PrivateScanDashboard>;
};

export type GetScanLogDashboardResponse = GetScanLogDashboardResponses[keyof GetScanLogDashboardResponses];

export type GetTicketVerificationLogsData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/v1/events/{event_id}/private-verification-logs';
};

export type GetTicketVerificationLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketVerificationLogsError = GetTicketVerificationLogsErrors[keyof GetTicketVerificationLogsErrors];

export type GetTicketVerificationLogsResponses = {
    /**
     * Successful Response
     */
    200: PageTicketVerificationLog;
};

export type GetTicketVerificationLogsResponse = GetTicketVerificationLogsResponses[keyof GetTicketVerificationLogsResponses];

export type GetPublicEventScanDashboardData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/public-scan-dashboard';
};

export type GetPublicEventScanDashboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicEventScanDashboardError = GetPublicEventScanDashboardErrors[keyof GetPublicEventScanDashboardErrors];

export type GetPublicEventScanDashboardResponses = {
    /**
     * Successful Response
     */
    200: PublicScanDashboard;
};

export type GetPublicEventScanDashboardResponse = GetPublicEventScanDashboardResponses[keyof GetPublicEventScanDashboardResponses];

export type GetPublicTicketVerificationLogsData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: {
        owner_name?: string | null;
        date?: string | null;
        page?: number;
        size?: number;
    };
    url: '/v1/events/{event_id}/public-verification-logs';
};

export type GetPublicTicketVerificationLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPublicTicketVerificationLogsError = GetPublicTicketVerificationLogsErrors[keyof GetPublicTicketVerificationLogsErrors];

export type GetPublicTicketVerificationLogsResponses = {
    /**
     * Successful Response
     */
    200: PagePublicTicketVerificationLog;
};

export type GetPublicTicketVerificationLogsResponse = GetPublicTicketVerificationLogsResponses[keyof GetPublicTicketVerificationLogsResponses];

export type AddStaffToEventData = {
    body: AddStaffToEvent;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/staffs';
};

export type AddStaffToEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddStaffToEventError = AddStaffToEventErrors[keyof AddStaffToEventErrors];

export type AddStaffToEventResponses = {
    /**
     * Successful Response
     */
    200: AddOrRemoveEventStaffResponse;
};

export type AddStaffToEventResponse = AddStaffToEventResponses[keyof AddStaffToEventResponses];

export type RemoveStaffFromEventData = {
    body?: never;
    path: {
        event_id: string;
        staff_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/staffs/{staff_id}';
};

export type RemoveStaffFromEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveStaffFromEventError = RemoveStaffFromEventErrors[keyof RemoveStaffFromEventErrors];

export type RemoveStaffFromEventResponses = {
    /**
     * Successful Response
     */
    200: AddOrRemoveEventStaffResponse;
};

export type RemoveStaffFromEventResponse = RemoveStaffFromEventResponses[keyof RemoveStaffFromEventResponses];

export type PublicCheckInData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}/public-check-in';
};

export type PublicCheckInErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicCheckInError = PublicCheckInErrors[keyof PublicCheckInErrors];

export type PublicCheckInResponses = {
    /**
     * Successful Response
     */
    200: PublicCheckInResponse;
};

export type PublicCheckInResponse2 = PublicCheckInResponses[keyof PublicCheckInResponses];

export type LoginForAccessTokenData = {
    body: BodyLoginForAccessTokenV1AuthTokenPost;
    path?: never;
    query?: never;
    url: '/v1/auth/token';
};

export type LoginForAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenError = LoginForAccessTokenErrors[keyof LoginForAccessTokenErrors];

export type LoginForAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenResponse = LoginForAccessTokenResponses[keyof LoginForAccessTokenResponses];

export type AuthenticationData = {
    body: BodyAuthenticationV1AuthLoginPost;
    path?: never;
    query?: {
        name?: unknown;
    };
    url: '/v1/auth/login';
};

export type AuthenticationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthenticationError = AuthenticationErrors[keyof AuthenticationErrors];

export type AuthenticationResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthenticationResponse = AuthenticationResponses[keyof AuthenticationResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh_token';
};

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateTicketTypeData = {
    body: CreateTicketType;
    path?: never;
    query?: never;
    url: '/v1/ticket-types';
};

export type CreateTicketTypeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketTypeError = CreateTicketTypeErrors[keyof CreateTicketTypeErrors];

export type CreateTicketTypeResponses = {
    /**
     * Successful Response
     */
    200: HetuModelsTicketTypeModelTicketType;
};

export type CreateTicketTypeResponse = CreateTicketTypeResponses[keyof CreateTicketTypeResponses];

export type DeleteTicketTypeData = {
    body?: never;
    path: {
        ticket_type_id: string;
    };
    query?: never;
    url: '/v1/ticket-types/{ticket_type_id}';
};

export type DeleteTicketTypeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTicketTypeError = DeleteTicketTypeErrors[keyof DeleteTicketTypeErrors];

export type DeleteTicketTypeResponses = {
    /**
     * Successful Response
     */
    200: DeleteTicketType;
};

export type DeleteTicketTypeResponse = DeleteTicketTypeResponses[keyof DeleteTicketTypeResponses];

export type AddTicketDateData = {
    body: AddOrDeleteDate;
    path: {
        ticket_type_id: string;
    };
    query?: never;
    url: '/v1/ticket-types/{ticket_type_id}/add-date';
};

export type AddTicketDateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTicketDateError = AddTicketDateErrors[keyof AddTicketDateErrors];

export type AddTicketDateResponses = {
    /**
     * Successful Response
     */
    200: HetuModelsTicketTypeModelTicketType;
};

export type AddTicketDateResponse = AddTicketDateResponses[keyof AddTicketDateResponses];

export type RemoveTicketDateData = {
    body: AddOrDeleteDate;
    path: {
        ticket_type_id: string;
    };
    query?: never;
    url: '/v1/ticket-types/{ticket_type_id}/remove-date';
};

export type RemoveTicketDateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveTicketDateError = RemoveTicketDateErrors[keyof RemoveTicketDateErrors];

export type RemoveTicketDateResponses = {
    /**
     * Successful Response
     */
    200: HetuModelsTicketTypeModelTicketType;
};

export type RemoveTicketDateResponse = RemoveTicketDateResponses[keyof RemoveTicketDateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};