// This file is auto-generated by @hey-api/openapi-ts

export type BodyAuthenticationV1AuthLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyLoginForAccessTokenV1AuthTokenPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyUploadImageV1ImagesUploadPost = {
    /**
     * Image file to upload
     */
    file: Blob | File;
};

export type ChangedPassword = {
    current_password: string;
    new_password: string;
};

export type EventCreate = {
    name: string;
    description: string | null;
    event_type: string;
    location?: string | null;
    ticket_types?: Array<TicketTypeInput> | null;
    start_date: Date;
    end_date: Date;
    booking_start_date: Date;
    booking_end_date: Date;
};

export type EventResponse = {
    name: string;
    image_id?: PydanticObjectId | null;
    description: string | null;
    event_type: string;
    location?: string | null;
    start_date: Date;
    end_date: Date;
    booking_start_date: Date;
    booking_end_date: Date;
    created_by?: PydanticObjectId | null;
    id: PydanticObjectId;
    ticket_types?: Array<TicketTypeDb>;
};

export type EventUpdate = {
    name?: string | null;
    image_id?: PydanticObjectId | null;
    description?: string | null;
    location?: string | null;
    event_type?: string | null;
    start_date?: Date | null;
    end_date?: Date | null;
    booking_start_date?: Date | null;
    booking_end_date?: Date | null;
    ticket_types?: Array<TicketTypeInput | TicketTypeDb> | null;
};

export type FilePath = {
    file_name: string;
    content_type: string;
    file_id: PydanticObjectId;
};

export type HttpValidationError = {
    errors?: Array<ValidationError>;
};

export type ImageUploadResponse = {
    id: PydanticObjectId;
    document_id: PydanticObjectId;
    file_path: FilePath;
    content_type: string;
    upload_date: Date;
};

export type PageEventResponse = {
    items: Array<EventResponse>;
    total: number | null;
    page: number | null;
    size: number | null;
    pages?: number | null;
};

export type PydanticObjectId = string;

export type RegisteredUser = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    status: string;
    credit: number;
    roles?: Array<string>;
    password: string;
    confirm_password: string;
};

export type TicketTypeDb = {
    name: string;
    total: number;
    price: number;
    remaining: number;
    ticket_id?: string;
};

export type TicketTypeInput = {
    name: string;
    total: number;
    price: number;
    remaining: number;
};

export type Token = {
    access_token: string;
    refresh_token: string;
    token_type: string;
    expires_in: number;
    expires_at: Date;
    scope: string;
    issued_at: Date;
};

export type UpdatedUser = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    status: string;
    credit: number;
    roles: Array<string>;
};

export type User = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    status: string;
    credit: number;
    id?: PydanticObjectId;
    last_login_date?: Date | null;
    roles: Array<string>;
};

export type UserList = {
    users: Array<User>;
    count: number;
    current_page?: number;
    total_page?: number;
};

export type UserTicketDetailResponse = {
    id: PydanticObjectId;
    ticket_type_id: string;
    ticket_name: string;
    quantity: number;
    price_per_ticket: number;
    total_price: number;
    event_start_date: Date;
    event_end_date: Date;
    purchase_date: Date;
    is_checked_in: boolean;
    checked_in_date: Date | null;
    status: string;
    user?: User | null;
    event?: EventResponse | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginForAccessTokenData = {
    body: BodyLoginForAccessTokenV1AuthTokenPost;
    path?: never;
    query?: never;
    url: '/v1/auth/token';
};

export type LoginForAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenError = LoginForAccessTokenErrors[keyof LoginForAccessTokenErrors];

export type LoginForAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenResponse = LoginForAccessTokenResponses[keyof LoginForAccessTokenResponses];

export type AuthenticationData = {
    body: BodyAuthenticationV1AuthLoginPost;
    path?: never;
    query?: {
        name?: unknown;
    };
    url: '/v1/auth/login';
};

export type AuthenticationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthenticationError = AuthenticationErrors[keyof AuthenticationErrors];

export type AuthenticationResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthenticationResponse = AuthenticationResponses[keyof AuthenticationResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh_token';
};

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadImageData = {
    body: BodyUploadImageV1ImagesUploadPost;
    path?: never;
    query?: {
        /**
         * Event ID to associate with the image
         */
        event_id?: string | null;
    };
    url: '/v1/images/upload';
};

export type UploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Successful Response
     */
    201: ImageUploadResponse;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type DeleteImageData = {
    body?: never;
    path: {
        image_id: string;
    };
    query?: never;
    url: '/v1/images/{image_id}';
};

export type DeleteImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteImageError = DeleteImageErrors[keyof DeleteImageErrors];

export type DeleteImageResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteImageResponse = DeleteImageResponses[keyof DeleteImageResponses];

export type GetImageData = {
    body?: never;
    path: {
        image_id: string;
    };
    query?: never;
    url: '/v1/images/{image_id}';
};

export type GetImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageError = GetImageErrors[keyof GetImageErrors];

export type GetImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserTicketByIdData = {
    body?: never;
    path: {
        user_ticket_id: string;
    };
    query?: never;
    url: '/v1/user_tickets/{user_ticket_id}';
};

export type GetUserTicketByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserTicketByIdError = GetUserTicketByIdErrors[keyof GetUserTicketByIdErrors];

export type GetUserTicketByIdResponses = {
    /**
     * Successful Response
     */
    200: UserTicketDetailResponse;
};

export type GetUserTicketByIdResponse = GetUserTicketByIdResponses[keyof GetUserTicketByIdResponses];

export type GetUserTicketsData = {
    body?: never;
    path?: never;
    query?: {
        user_id?: string;
    };
    url: '/v1/user_tickets';
};

export type GetUserTicketsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserTicketsError = GetUserTicketsErrors[keyof GetUserTicketsErrors];

export type GetUserTicketsResponses = {
    /**
     * Successful Response
     */
    200: Array<UserTicketDetailResponse>;
};

export type GetUserTicketsResponse = GetUserTicketsResponses[keyof GetUserTicketsResponses];

export type GetEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
        name?: string | null;
        event_type?: string | null;
        start_date_from?: string | null;
        start_date_to?: string | null;
    };
    url: '/v1/events';
};

export type GetEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventsError = GetEventsErrors[keyof GetEventsErrors];

export type GetEventsResponses = {
    /**
     * Successful Response
     */
    200: PageEventResponse;
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type CreateEventData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/v1/events';
};

export type CreateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * Successful Response
     */
    200: EventResponse;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type DeleteEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEventError = DeleteEventErrors[keyof DeleteEventErrors];

export type DeleteEventResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteEventResponse = DeleteEventResponses[keyof DeleteEventResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type GetEventByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventByIdError = GetEventByIdErrors[keyof GetEventByIdErrors];

export type GetEventByIdResponses = {
    /**
     * Successful Response
     */
    200: EventResponse;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];

export type UpdateEventData = {
    body: EventUpdate;
    path: {
        event_id: string;
    };
    query?: never;
    url: '/v1/events/{event_id}';
};

export type UpdateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEventError = UpdateEventErrors[keyof UpdateEventErrors];

export type UpdateEventResponses = {
    /**
     * Successful Response
     */
    200: EventResponse;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}';
};

export type GetByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByIdError = GetByIdErrors[keyof GetByIdErrors];

export type GetByIdResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type GetAllData = {
    body?: never;
    path?: never;
    query?: {
        current_page?: number;
        limit?: number;
        username?: string | null;
        email?: string | null;
    };
    url: '/v1/users';
};

export type GetAllErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllError = GetAllErrors[keyof GetAllErrors];

export type GetAllResponses = {
    /**
     * Successful Response
     */
    200: UserList;
};

export type GetAllResponse = GetAllResponses[keyof GetAllResponses];

export type CreateData = {
    body: RegisteredUser;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type CreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type ChangePasswordData = {
    body: ChangedPassword;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/change_password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type UpdateData = {
    body: UpdatedUser;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/update';
};

export type UpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type SetStatusData = {
    body?: never;
    path: {
        user_id: PydanticObjectId;
    };
    query?: {
        status?: string;
    };
    url: '/v1/users/{user_id}/set_status';
};

export type SetStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetStatusError = SetStatusErrors[keyof SetStatusErrors];

export type SetStatusResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SetStatusResponse = SetStatusResponses[keyof SetStatusResponses];

export type SetRoleData = {
    body?: never;
    path: {
        user_id: PydanticObjectId;
    };
    query: {
        role: string;
        action: string;
    };
    url: '/v1/users/{user_id}/set_role';
};

export type SetRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRoleError = SetRoleErrors[keyof SetRoleErrors];

export type SetRoleResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type SetRoleResponse = SetRoleResponses[keyof SetRoleResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};